CREATE TABLE app_studio_space (
  studio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  size TEXT NOT NULL CHECK (size IN ('Small','Medium','Large')),
  description TEXT NOT NULL,
  monthly_rate NUMERIC(10,2) NOT NULL CHECK (monthly_rate >= 0),
  image_path VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO app_studio_space (slug,name,size,description,monthly_rate,image_path) VALUES
  ('paris','Paris','Large','A large sized maker studio for ambitious builds and small teams.',1200.00,'/assets/space-paris.webp'),
  ('coruscant','Coruscant','Medium','A medium sized maker studio with bench space and natural light.',750.00,'/assets/space-coruscant.webp'),
  ('harkonnen','Harkonnen','Small','A small sized maker studio for precise, independent work.',350.00,'/assets/space-harkonnen.webp')
ON CONFLICT (slug) DO UPDATE SET
  name=EXCLUDED.name,
  size=EXCLUDED.size,
  description=EXCLUDED.description,
  monthly_rate=EXCLUDED.monthly_rate,
  image_path=EXCLUDED.image_path,
  active=TRUE;

CREATE TABLE app_studio_lease (
  lease_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  studio_id INTEGER NOT NULL REFERENCES app_studio_space(studio_id),
  userid INTEGER NOT NULL REFERENCES "user"(userid),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  term_months INTEGER NOT NULL CHECK (term_months > 0),
  monthly_rate NUMERIC(10,2) NOT NULL CHECK (monthly_rate >= 0),
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed','cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_date > start_date)
);

-- Leases use half-open date ranges: the next lease may start on the prior end date.
ALTER TABLE app_studio_lease ADD CONSTRAINT app_studio_lease_no_overlap
  EXCLUDE USING gist (studio_id WITH =, daterange(start_date,end_date,'[)') WITH &&)
  WHERE (status='confirmed');
CREATE INDEX app_studio_lease_user_start ON app_studio_lease(userid,start_date DESC);
CREATE INDEX app_studio_lease_studio_start ON app_studio_lease(studio_id,start_date) WHERE status='confirmed';
