import {afterAll,beforeAll,expect,test,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter} from 'react-router-dom';
import App from '../../src/App';
import {createBrowserBridge} from '../../../backend/test/helpers/browserBridge';
let bridge:Awaited<ReturnType<typeof createBrowserBridge>>;
beforeAll(async()=>{bridge=await createBrowserBridge();},120000);
afterAll(async()=>{cleanup();vi.unstubAllGlobals();await bridge?.close();},30000);
test('staff equipment UI saves four-hour reservation for selected member and does not list it as staff-owned',async()=>{
 vi.stubGlobal('fetch',bridge.fetch);
 const login=await bridge.fetch('/api/auth/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:'admin'})});
 expect(login.status).toBe(200);
 const staff=(await login.json()).data.user.id;
 await bridge.pool.query("UPDATE user_role SET roleid=(SELECT roleid FROM role WHERE role='staff') WHERE userid=$1",[staff]);
 const member=(await bridge.pool.query(`SELECT userid FROM "user" WHERE email='demo.member@collaboratory.invalid'`)).rows[0].userid;
 render(<MemoryRouter initialEntries={['/reservations']}><App/></MemoryRouter>);
 const user=userEvent.setup();
 await user.click(await screen.findByRole('button',{name:/3D Printer/}));
 const modal=within(screen.getByRole('dialog'));
 await user.type(modal.getByLabelText(/Book for member ID/),String(member));
 const start=new Date(Date.now()+3*86400000);start.setHours(14,0,0,0);
 const local=[start.getFullYear(),String(start.getMonth()+1).padStart(2,'0'),String(start.getDate()).padStart(2,'0')].join('-')+'T14:00';
 fireEvent.change(modal.getByLabelText(/Start date and time/),{target:{value:local}});
 await user.selectOptions(modal.getByLabelText('Duration'),'4');
 await user.click(modal.getByRole('button',{name:'Confirm reservation'}));
 await screen.findByText('Reservation saved for 3D Printer for member #'+member+'.');
 const rows=(await bridge.pool.query('SELECT userid,endtime-starttime AS duration FROM reservation')).rows;
 expect(rows).toHaveLength(1);expect(rows[0].userid).toBe(member);expect(rows[0].duration.hours).toBe(4);
 expect(await screen.findByText(/No reservations yet/)).toBeTruthy();
});
